apiVersion: v1 
kind: Pod
metadata:
  name: pod-aff
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: project
            operator: In
            values:
            - roboshop
  containers:
  - name: nginx
    image: nginx