apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    Project: roboshop
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  replicas: 4
  selector:
    matchLabels:
      Project: roboshop
  template:
    metadata:
      labels:
        Project: roboshop
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: project
                operator: In
                values:
                - roboshop
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: nginx-dep
        image: nginx