apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    Project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      Project: roboshop
  template:
    metadata:
      labels:
        Project: roboshop
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: Project
                operator: In
                values:
                - roboshop
            topologyKey: topology.kubernetes.io/zone

        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: Project
                operator: In
                values:
                - dev
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: nginx-dep
        image: nginx