apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment 
  labels:
    Project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      Project: roboshop
  template:
    metadata:
      labels:
        Project: roboshop
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: diskType
                operator: In
                values:
                - ssd
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: diskType
                operator: In
                values:
                - ssd
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nginx-dep
        image: nginx